### ISSUE TITLE
Matplotlib Version

### ISSUE THREAD

**Issue by loretoparisi** [f90/Wave-U-Net#12]
When un Ubuntu, using current requirements with `sudo -H pip install -r requirements` the latest matplotlib will be installed (3.3). But since we need Python 2.7, the requirements should explicitly specify a lower version of it:

```sh
matplotlib<3.0
```

so that the 2.2.3 will be installed:

```sh
$ python -c "import matplotlib as mp; print mp.__version__"
2.2.3
```

**Comment by f90** [comment]
Personally I didnt have this issue as it seems on my Ubuntu matplotlib was installed with 2.2.3 automatically when using the current requirements. But to ensure this runs smoothly on all kinds of different Linux distributions, I added your suggested line to the requirements file.

Could you check with a fresh virtual environment (``virtualenv test``, ``source test/bin/activate``, ``pip install -r PATH_TO_REQUIREMENTS.TXT``) on your end whether this fixed the issue? Thanks

**Comment by loretoparisi** [comment]
@f90 yes, confirmed that this works ok in `virtualenv`, but it does not in the current environment. Let's say that for this case only (Matplot lib 3.0 requires Python 3.5 - that for me it's crazy btw), having it specified explicitly it can help. Thank you!
