### ISSUE TITLE
Pretrained models NotFoundError

### ISSUE THREAD

**Issue by beantowel** [f90/Wave-U-Net#14]
run the command:
`python2 Predict.py with cfg.full_multi_instrument`
results in:
`NotFoundError: Key separator/conv1d_26/bias not found in checkpoint`
however, the command `python2 Predict.py with cfg.full_44KHz` will terminate with no errors.

**Comment by f90** [comment]
As shown in the readme, by default the 44KHz singing voice separation model is loaded, so its okay to not put a ``model_path`` parameter. But in your case you have to put the path to the model checkpoint file. So it would be

``python Predict.py with cfg.full_multi_instrument model_path="checkpoints/full_multi_instrument/full_multi_instrument-134067``

Does that make sense/resolve your problem?

**Comment by beantowel** [comment]
thank you, it solves the problem, missed that part of readme 0v0
