### ISSUE TITLE
Question - About audio input resampling

### ISSUE THREAD

**Issue by loretoparisi** [f90/Wave-U-Net#17]
Hello, according to the util.load method https://github.com/f90/Wave-U-Net/blob/1dd50fdce39edb68c43c85413835a608432070d9/Utils.py#L110
you are loading the audio file through `librosa.load` but not doing any resampling here, while running a resampling by defaults of `sr=22050` with `scypy. resample_poly` method.
I'm using `produce_source_estimates` where  the audio is loaded like

```python
audio, sr = Utils.load(input_path, sr=None, mono=False)
```

so it's not using any resampling by defaults. Any reason for that? In my CNN I have a resampling of 12KHz of the input, so can I do apply this resampling?

**Comment by f90** [comment]
> so it's not using any resampling by defaults

This is not true, although it might look that way at first. After this, ``predict`` function and within that, ``predict_track`` is called, which takes care of downsampling the input audio as necessary for the model!

https://github.com/f90/Wave-U-Net/blob/master/Evaluate.py#L120

> In my CNN I have a resampling of 12KHz of the input, so can I do apply this resampling?

I don't exactly understand your question. Where is that model defined? Within this code framework? If so, then you don't need to worry as the input audio will be downsampled for your model appropriately beforehand

**Comment by loretoparisi** [comment]
@f90 got it. So basically I'm using your raw output to a feed a CNN classifier. In my classifier for computation needs I did a resampling to 12KHz. Considering that your raw audio was 22050 I was thinking to do resampling at 12 in the first step, hence in the Wave-U Net, before passing the output to my CNN...does it make sense for you?

**Comment by f90** [comment]
Do you want to save the Wave-U-Net outputs first, downsample them, and then train the CNN classifier? Or do you want to use the Wave-U-Net "on-the-fly", meaning that while training the CNN classifier, the Wave-U-Net is applied constantly in the background to provide you with your outputs? If it's the former, you could iterate through your audio dataset and feed each track to the Wave-U-Net using ``Predict.py`` interface, then downsample the results yourselves to 12KHz. After this is all done, you can then train the CNN on the outputs. So in this way you don't need to modify any of my code

**Comment by loretoparisi** [comment]
yes it's the second case, the wave is not saved, I take the output of the wave-u-net and feed the cnn classifier immediately. This to save I/O and disk operations, so I keep all in memory while processing the audio file...the first approach should be easier though.

**Comment by f90** [comment]
Ah OK, so the classifier is also a Tensorflow model and you want to run it all in one session? In that case you want to keep everything as is, except modify

https://github.com/f90/Wave-U-Net/blob/master/Evaluate.py#L73

where the Wave-U-Net output gets resampled - you can change that so it always gets resampled to 12KHz, and then feed it into your model. Note that the code here actually starts a new TF session each time though - which if you are training your own model seems unnecessary, so you might want to remove that stuff too so both models are in the same persistent session

**Comment by loretoparisi** [comment]
Thank you for your help! It makes sense to run everything in the same session! 💯
