### ISSUE TITLE
Evaluation mertirc of models

### ISSUE THREAD

**Issue by Jaesuny** [f90/Wave-U-Net#18]
To evaluate model performance, did you average segment-wise SDRs over the whole dataset using below function?

https://github.com/f90/Wave-U-Net/blob/master/Evaluate.py#L207
```python
def compute_mean_metrics(json_folder, compute_averages=True):
    files = glob.glob(os.path.join(json_folder, "*.json"))
    sdr_inst_list = None
    for path in files:
        #print(path)
        with open(path, "r") as f:
            js = json.load(f)

        if sdr_inst_list is None:
            sdr_inst_list = [list() for _ in range(len(js["targets"]))]

        for i in range(len(js["targets"])):
            sdr_inst_list[i].extend([np.float(f['metrics']["SDR"]) for f in js["targets"][i]["frames"]])

    #return np.array(sdr_acc), np.array(sdr_voc)
    sdr_inst_list = [np.array(sdr) for sdr in sdr_inst_list]

    if compute_averages:
        return [(np.nanmedian(sdr), np.nanmedian(np.abs(sdr - np.nanmedian(sdr))), np.nanmean(sdr), np.nanstd(sdr)) for sdr in sdr_inst_list]
    else:
        return sdr_inst_list
```

**Comment by f90** [comment]
Yes, you can apply this function by pointing ``json_folder`` to the folder path where the MUSDB evaluation function drops its json files for all the songs after measuring the separation quality (see ``produce_musdb_source_estimates`` function and last line in ``Training.py``).

It computes all the numbers shown in the paper (Mean, SD, Median, MAD), while throwing away NaN segments.

Hope that is clear now? I think I'll add a short documentation to the code...

**Comment by f90** [comment]
I added some documentation to the function now. Please pull the latest version of the code and see if you have any questions left as to how to use it.

**Comment by Jaesuny** [comment]
Thank you for your reply.
It's clear now.
