### ISSUE TITLE
InvalidArgumentError in multi_instrument Training

### ISSUE THREAD

**Issue by theroggio** [f90/Wave-U-Net#29]
I'm trying training with the musdb dataset on colab. At EPOCH 0 after printing the number of sep_variables and the number of variables it throws me this error.

/usr/local/lib/python2.7/dist-packages/sacred/config/captured_function.pyc in captured_function(wrapped, instance, args, kwargs)
     44         start_time = time.time()
     45     # =================== run actual function =================================
---> 46     result = wrapped(*args, **kwargs)
     47     # =========================================================================
     48     if wrapped.logger is not None:

/content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.pyc in run(cfg)
    164     print(model_config)
    165     # Optimize in a supervised fashion until validation loss worsens
--> 166     sup_model_path, sup_loss = optimise(model_config, idd)
    167     print("Supervised training finished! Saved model at " + sup_model_path + ". Performance: " + str(sup_loss))
    168 

/usr/local/lib/python2.7/dist-packages/sacred/config/captured_function.pyc in captured_function(wrapped, instance, args, kwargs)
     44         start_time = time.time()
     45     # =================== run actual function =================================
---> 46     result = wrapped(*args, **kwargs)
     47     # =========================================================================
     48     if wrapped.logger is not None:

/content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.pyc in optimise(model_config, experiment_id)
    136         while worse_epochs < model_config["worse_epochs"]: # Early stopping on validation set after a few epochs
    137             print("EPOCH: " + str(epoch))
--> 138             model_path = train(model_config, experiment_id, model_path)
    139             curr_loss = Test.test(model_config, model_folder=str(experiment_id), partition="valid", load_model=model_path)
    140             epoch += 1

/usr/local/lib/python2.7/dist-packages/sacred/config/captured_function.pyc in captured_function(wrapped, instance, args, kwargs)
     44         start_time = time.time()
     45     # =================== run actual function =================================
---> 46     result = wrapped(*args, **kwargs)
     47     # =========================================================================
     48     if wrapped.logger is not None:

/content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.pyc in train(model_config, experiment_id, load_model)
    104     for _ in range(model_config["epoch_it"]):
    105         # TRAIN SEPARATOR
--> 106         _, _sup_summaries = sess.run([separator_solver, sup_summaries])
    107         writer.add_summary(_sup_summaries, global_step=_global_step)
    108 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Input to reshape is a tensor with 0 values, but the requested shape has 2099164
	 [[{{node Reshape}}]]
	 [[node IteratorGetNext (defined at /content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.py:42) ]]
	 [[node IteratorGetNext (defined at /content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.py:42) ]]

But I'm 100% sure to give the correct paths and that the configuration has the right parameters. I've tried printing the sep_input_shape and sep_output_shapes and they're both 3-dimensional arrays with proper dimensions. Is there something i'm missing?

**Comment by f90** [comment]
Can you give me the input and output shapes in your case?
Also please give me the command you are using to run the Training, so I can see the configuration you are using.
Did you modify any of the code so far?

**Comment by theroggio** [comment]
I've only changed the paths to match mine. 
This is how I set up the configuration:

c = Config.cfg()
c['model_config']['output_type'] = 'difference'
c['model_config']['context'] = True
c['model_config']['upsampling'] = 'linear'
c['model_config']['mono_downmix'] = False
c['model_config']['task'] = 'multi_instrument'
c['model_config']['source_names'] = ['bass' , 'drums', 'others' , 'vocals']
c['model_config']['num_sources'] = len(c['model_config']['source_names'])
c['model_config']['num_channels'] = 2

Colab does not have a 'command line' so this was a fast way to modify the fields required for the multi instrument.  Then I import the Training.py file and use 

Training.run(c) 

disc_input_shape = [16, 16384, 0]
sep_ input_shape = [    16 147443      2]
sep_output_shape = [   16 16389     2]

**Comment by f90** [comment]
So you calculate the shape arrays yourself manually? It looks like you should use my own code to compute these dynamically based on the model configuration - that works for all the different settings and also prevents mistakes like the one i see in your case here: the number of output channels has to be num_sources*num_channels, so 2*4=8 in your case. But you set it to 2 in sep_output_shape. Try again with 8.

**Comment by theroggio** [comment]
No, I just wrote there the shapes but they're computed by the code. 
I tried forcing the sep_output_shape to have last value = 8, but it throws the same exact error.

**Comment by f90** [comment]
```
c['model_config']['source_names'] = ['bass' , 'drums', 'others' , 'vocals']
```
there is a spelling error here with "others", see the original code:
```
model_config["source_names"] = ["bass", "drums", "other", "vocals"]
```

**Comment by theroggio** [comment]
It keeps on giving me this error even after correcting the spelling mistake

InvalidArgumentError: Input to reshape is a tensor with 0 values, but the requested shape has 2099164
	 [[{{node Reshape}}]]
	 [[node IteratorGetNext (defined at /content/drive/My Drive/Wave-U-Net-master/Wave-U-Net-master/Training.py:45) ]]

**Comment by f90** [comment]
It sounds like the dataset might be not located at the path that is given. Is the ``data_path`` config correctly set and contains a subfolder such as ``task_voice_sr_44100_mono_False`` which then has three subfolders that contain tfrecords files?

Otherwise something went wrong during the preprocessing of the MUSDB dataset. Similarly if the MUSDB dataset path was not correctly set, it will not be able to create any tfrecords files in the first place and you might encounter this error. When you first run the code, there should be a long waiting period where it preprocesses the data before starting the actual training. Was this the case for you? If not, there is definitely something wrong with the MUSDB data loading.

**Comment by f90** [comment]
If all else fails, try running it normally without Colab since Colab makes it much harder to run the code properly, apparently... Then if everything works, carefully transfer to Colab. That way we at least know whether Colab/the custom config you built is the issue or not.

**Comment by f90** [comment]
Closing this for now due to lack of activity
