### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by MatthewWEdwards** [f90/Wave-U-Net#34]
Hi,

I am planning on using this code in a personal Python 3 project. Are the maintainers of this repository interested in a Python 3 rewrite? Does the current implementation support Python 3? (I have not dug into the code deeply, so I am uncertain if this package is compatible with Python 3.) If work is needed to support Python 3, I'd be happy to contribute

**Comment by f90** [comment]
I just updated to Python 3.6.8 using the 2to3 library, can you try to work with the new code a bit and see if there are any errors? Thank you!

**Comment by MatthewWEdwards** [comment]
Will do, thank you for the quick response

**Comment by f90** [comment]
@MatthewWEdwards Is everything running normally? Then I can close this issue?

**Comment by MatthewWEdwards** [comment]
Inference appears to work. I haven't had the chance to experiment with training. I think it is alright to close the issue, and I will open a new one if I encounter any issues.

Thanks for the software and help!

**Comment by f90** [comment]
OK cool, i think you can reopen this issue in case you run into Python 3-specific trouble in the future, instead of having to open a new one. 
Thanks!
