### ISSUE TITLE
How to run the codes in multi GPUs?

### ISSUE THREAD

**Issue by Tinglok** [f90/Wave-U-Net#35]
@f90 Thank you for your previous work, what you did save me a lot of time. But now I want to try to run the codes on multiple GPUs, but I found that I can't run directly. So I decided to modify the codes, but only to find that TensorFlow is not good for multi-GPUs support. Since you are the person who wrote these codes, I wonder if you could change the code to run on multiple GPUs? Thanks again.

**Comment by f90** [comment]
Multi-GPU support is not planned for now, but I don't think it should be very difficult in Tensorflow to adapt the code? What issues do you have exactly when modifying the code?

I might release another implementation in Pytorch at some point that could have multi-GPU support, but no guarantees...

**Comment by Tinglok** [comment]
Hi, f90,
I am trying to write multi-GPUs support with a framework called [horovod](https://github.com/horovod/horovod), now I am working on it.

**Comment by f90** [comment]
Sounds good, let me know when you're finished in case there is some code we could merge into this repository to have multi-GPU support!
