### ISSUE TITLE
 scikits.audiolab: failed

### ISSUE THREAD

**Issue by loretoparisi** [f90/Wave-U-Net#7]
I get this error while installing required `scikits.audiolab`

`Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-BXHQz4/scikits.audiolab/`

This is because `scikits.audiolab` needs `libsndfile`, so first of all this one must be installed:

```sh
brew install libsndfile
```

**Comment by f90** [comment]
Thanks for reporting this. I will include a notice in the readme file that libsndfile needs to be properly installed on your system previously to installing the required Python packages. Users can then refer to the libsndfile documentation for the installation, so I don't need to clutter my own instructions with this.
